name: CirculanteParcial

on:
  schedule:
    -   cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  
    - name: Instalar dependencias
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ejecutar Script de Scraping
      run: |
        python CirculanteParcial.py
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Datos del circulante actualizados
